# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0045_project_services_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedResource',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('structure.servicesettings',),
        ),
    ]
