# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0046_shared_service_settings_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesettings',
            name='allow_backend_fields_editing',
            field=models.BooleanField(default=True),
        ),
    ]
