# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 17:04
from __future__ import unicode_literals

from django.db import migrations
import nodeconductor.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0048_remove_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesettings',
            name='backend_url',
            field=nodeconductor.core.fields.ExtendedURLField(blank=True, null=True),
        ),
    ]
