# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0050_reset_cloud_spl_quota_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agreement_number',
            field=models.PositiveIntegerField(null=True, blank=True, unique=True),
        ),
    ]
